apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-tls-server
  namespace: etcd
spec:
  secretName: etcd-server-certs
  subject:
    organizations:
    - m3o
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - "etcd.etcd.svc.cluster.local"
  -  "*.etcd-headless.etcd.svc.cluster.local"
  -  "etcd"
  issuerRef:
    name: ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-tls-client
  namespace: etcd
spec:
  secretName: etcd-client-certs
  subject:
    organizations:
    - m3o
  dnsNames:
  - "etcd.etcd.svc.cluster.local"
  -  "*.etcd-headless.etcd.svc.cluster.local"
  -  "etcd"
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-tls-peer
  namespace: etcd
spec:
  secretName: etcd-peer-certs
  subject:
    organizations:
    - m3o
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - "etcd.etcd.svc.cluster.local"
  -  "*.etcd-headless.etcd.svc.cluster.local"
  -  "etcd"
  issuerRef:
    name: ca-issuer
