apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
  namespace: minio
spec:
  secretName: minio-tls
  subject:
    organizations:
    - m3o
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
  - "minio.minio.svc.cluster.local"
  -  "minio"
  issuerRef:
    name: ca
    kind: ClusterIssuer

